services:
  - type: web
    name: bizbroker-backend
    env: node
    plan: starter
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy || npx prisma db push
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bizbroker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://bizbroker-front.onrender.com
      - key: BACKEND_URL
        value: https://bizbroker-backend.onrender.com

databases:
  - name: bizbroker-db
    plan: starter
    databaseName: bizbroker
    user: bizbroker_user
